import {testGroup} from 'test-vir';
import {getSampleFilePath} from '../file-paths';
import {libraryStateMachine} from '../library-fsm';
import {readLibrary} from '../library-reader';

testGroup((runTest) => {
    const sampleLibraryFilePath = getSampleFilePath('library-example.xml');
    const sampleLibraryOutput = readLibrary(sampleLibraryFilePath, true);

    runTest({
        description: 'run library fsm',
        expect: [
            'Logging turned on.',
            'actionStateOrder: Before',
            'Starting with output {}',
            'Starting on state "WaitingForAList"',
            'currentState: WaitingForAList input: "?xml"',
            'currentState: WaitingForAList input: "!DOCTYPE plist PUBLIC \\"-//Apple Computer//DTD PLIST 1.0//EN\\" \\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\\""',
            'currentState: WaitingForAList input: "plist"',
            'currentState: WaitingForAList input: "dict"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Major Version"',
            'currentState: WaitingForAList input: "integer"',
            'currentState: WaitingForAList input: "-1"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Minor Version"',
            'currentState: WaitingForAList input: "integer"',
            'currentState: WaitingForAList input: "-1"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Application Version"',
            'currentState: WaitingForAList input: "string"',
            'currentState: WaitingForAList input: "0.0.0.0"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Date"',
            'currentState: WaitingForAList input: "date"',
            'currentState: WaitingForAList input: "1970-01-01T00:00:00.000Z"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Features"',
            'currentState: WaitingForAList input: "integer"',
            'currentState: WaitingForAList input: "-1"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Show Content Ratings"',
            'currentState: WaitingForAList input: "true"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Library Persistent ID"',
            'currentState: WaitingForAList input: "string"',
            'currentState: WaitingForAList input: "XXX"',
            'currentState: WaitingForAList input: "key"',
            'currentState: WaitingForAList input: "Tracks"',
            'currentState: WaitingForTracksDict input: "dict"',
            'currentState: WaitingForNextTrack input: "key"',
            'currentState: WaitingForNextTrack input: "1"',
            'currentState: WaitingForNextTrack input: "dict"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Track ID"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Size"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "111111"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Total Time"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "111"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Year"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "1970"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "BPM"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "11"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Date Modified"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Date Added"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Bit Rate"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "256"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Sample Rate"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "44100"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Play Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "111"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Play Date"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Play Date UTC"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Skip Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Skip Date"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Rating"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "100"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album Rating"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "100"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album Rating Computed"',
            'currentState: ParsingTrack input: "true"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Persistent ID"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "XXXX"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Track Type"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "File"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "File Type"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "-1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "File Folder Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Library Folder Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Name"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Song 1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Artist"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Same Artist 1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album Artist"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Album Artist 1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Composer"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Composer 1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Album 1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Genre"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Genre 1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Kind"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "AAC audio file"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Location"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "file:///Volumes/sample/path/sample1.m4a"',
            'currentState: ParsingTrack input: "key"',
            'currentState: WaitingForNextTrack input: "2"',
            'currentState: WaitingForNextTrack input: "dict"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Track ID"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Size"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "222222"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Total Time"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "2222"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Year"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "1970"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "BPM"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "22"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Date Modified"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Date Added"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Bit Rate"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "256"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Sample Rate"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "44100"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Play Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "222"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Play Date"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Play Date UTC"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Skip Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Skip Date"',
            'currentState: ParsingTrack input: "date"',
            'currentState: ParsingTrack input: "1970-01-01T00:00:00.000Z"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Rating"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "100"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album Rating"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "100"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album Rating Computed"',
            'currentState: ParsingTrack input: "true"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Persistent ID"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "XXXX"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Track Type"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "File"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "File Type"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "-1"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "File Folder Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Library Folder Count"',
            'currentState: ParsingTrack input: "integer"',
            'currentState: ParsingTrack input: "0"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Name"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Song 2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Artist"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Same Artist 2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album Artist"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Album Artist 2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Composer"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Composer 2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Album"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Album 2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Genre"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "Sample Genre 2"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Kind"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "AAC audio file"',
            'currentState: ParsingTrack input: "key"',
            'currentState: ParsingTrack input: "Location"',
            'currentState: ParsingTrack input: "string"',
            'currentState: ParsingTrack input: "file:///Volumes/sample/path/sample2.m4a"',
            'currentState: ParsingTrack input: "key"',
            'currentState: WaitingForNextTrack input: "Playlists"',
            'currentState: WaitingForPlaylistArray input: "array"',
            'currentState: WaitingForNextPlaylist input: "dict"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Master"',
            'currentState: ParsingPlaylist input: "true"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Playlist ID"',
            'currentState: ParsingPlaylist input: "integer"',
            'currentState: ParsingPlaylist input: "123"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Playlist Persistent ID"',
            'currentState: ParsingPlaylist input: "string"',
            'currentState: ParsingPlaylist input: "XXX"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "All Items"',
            'currentState: ParsingPlaylist input: "true"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Visible"',
            'currentState: ParsingPlaylist input: "false"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Name"',
            'currentState: ParsingPlaylist input: "string"',
            'currentState: ParsingPlaylist input: "Library"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Playlist Items"',
            'currentState: WaitingForPlaylistItemsArray input: "array"',
            'currentState: ParsingPlaylistTracks input: "dict"',
            'currentState: ParsingPlaylistTracks input: "key"',
            'currentState: ParsingPlaylistTracks input: "Track ID"',
            'currentState: ParsingPlaylistTracks input: "integer"',
            'currentState: ParsingPlaylistTracks input: "1"',
            'currentState: ParsingPlaylistTracks input: "dict"',
            'currentState: ParsingPlaylistTracks input: "key"',
            'currentState: ParsingPlaylistTracks input: "Track ID"',
            'currentState: ParsingPlaylistTracks input: "integer"',
            'currentState: ParsingPlaylistTracks input: "2"',
            'currentState: ParsingPlaylistTracks input: "dict"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Playlist ID"',
            'currentState: ParsingPlaylist input: "integer"',
            'currentState: ParsingPlaylist input: "124"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Playlist Persistent ID"',
            'currentState: ParsingPlaylist input: "string"',
            'currentState: ParsingPlaylist input: "XXXXXX"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Distinguished Kind"',
            'currentState: ParsingPlaylist input: "integer"',
            'currentState: ParsingPlaylist input: "-1"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "All Items"',
            'currentState: ParsingPlaylist input: "true"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Name"',
            'currentState: ParsingPlaylist input: "string"',
            'currentState: ParsingPlaylist input: "Downloaded"',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Smart Info"',
            'currentState: ParsingPlaylist input: "data"',
            'currentState: ParsingPlaylist input: "\\n                    AAA\\n                "',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Smart Criteria"',
            'currentState: ParsingPlaylist input: "data"',
            'currentState: ParsingPlaylist input: "\\n                    AAAA\\n                "',
            'currentState: ParsingPlaylist input: "key"',
            'currentState: ParsingPlaylist input: "Playlist Items"',
            'currentState: WaitingForPlaylistItemsArray input: "array"',
            'currentState: ParsingPlaylistTracks input: "dict"',
            'currentState: ParsingPlaylistTracks input: "key"',
            'currentState: ParsingPlaylistTracks input: "Track ID"',
            'currentState: ParsingPlaylistTracks input: "integer"',
            'currentState: ParsingPlaylistTracks input: "1"',
            'currentState: ParsingPlaylistTracks input: "dict"',
            'currentState: ParsingPlaylistTracks input: "key"',
            'currentState: ParsingPlaylistTracks input: "Track ID"',
            'currentState: ParsingPlaylistTracks input: "integer"',
            'currentState: ParsingPlaylistTracks input: "2"',
        ],
        test: () => {
            return libraryStateMachine.runMachine(sampleLibraryOutput, {enableLogging: true}).logs;
        },
    });
});
